Numpy Kütüphanesi

*Veri analizi ve bilimsel hesaplamalarda kullanılır 

*Arrayler ve çok boyutlu arrayler üzerine yüksek performanslı işlemler yapılabilir


In [22]:
#NEDEN NUMPY?

a=[1,2,3,4]
b=[2,3,4,5]
ab=[]
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
print(ab)

import numpy as np 
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
print(a*b)

[2, 6, 12, 20]
[ 2  6 12 20]


.reshape() fonksiyonu ile arrayların boyutunu değiştirebiliriz

.shape ile arraylarin boyutunu öğrenebiliriz

.ndim ile arrayların boyut sayısını öğrenebiliriz

In [21]:

a=np.array([1,2,3,4,5,6,7,8,9])
multi=a.reshape(3,3)
print(multi)
print(multi.shape)
print(a.shape)
print(a.ndim )
print((multi.ndim))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(9,)
1
2


.concatenate() fonksiyonu ile birleştirme yapabiliriz

ayrıca axis=0 ile satır , axis=1 ile sütün bazında birleştirme yapar

In [28]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])
print(np.concatenate([x,y]))
a=np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a]))
print(np.concatenate([a,a], axis=1))

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


Array ayırma (splitting) 

.split() fonksiyonu ile array ayırma yapabiliriz

.vsplit() yatay ayırma 

.hsplit() dikey ayırma yapar

.arange() basit bir şekilde dizi olulturmamısı sağlar np.arrange(start,stop,step)

In [30]:
m=np.array([1,2,3,4,5,6,7,8,9])
print(np.split(m,[3,5]))
a,b,c=np.split(m,[3,5])
print(a)
print(b)
print(c)

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]
[1 2 3]
[4 5]
[6 7 8 9]


In [36]:
n=np.arange(16).reshape(4,4)
print(np.vsplit(n,[2]))
np.hsplit(n,[2])

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

.arange() basit bir şekilde dizi olulturmamısı sağlar  "np.arrange(start,stop,step)"

np.zeros() 0'lardan oluşan numpy dizisi oluşturmak için kullanılır

np.ones() 1'lerden oluşan numpy dizisi oluşturmak için kullanılır

np.linspace() bellir bir aralıkta sayı oluşturmak için kullanılır"(baş.,bitiş,bölünecek aralık)"


In [3]:
import numpy as np
print(np.arange(2,12,2))
print(np.zeros(5))
print(np.ones(5))
print(np.linspace(0,100,5))
print(np.random.randint(2,10,3))
npArray=np.arange(50)
npMulti=npArray.reshape(5,10)
print(npMulti.sum(axis=1))


[ 2  4  6  8 10]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[9 5 5]
[ 45 145 245 345 445]


Array sıralama için sort() fonksiyonu kullanılır

In [23]:
a=np.array([3,2,14,7,19,17,21,1])
print(a)
a.sort()
print(a)
m=np.random.normal(15,3,(3,3))
print(np.sort(m,axis=0))
print(np.sort(m,axis=1))

[ 3  2 14  7 19 17 21  1]
[ 1  2  3  7 14 17 19 21]
[[13.74954545 13.58876573 13.08098735]
 [13.75858987 14.76037893 15.25978172]
 [15.23414863 15.10693993 17.87985204]]
[[15.10693993 15.23414863 17.87985204]
 [13.58876573 13.75858987 15.25978172]
 [13.08098735 13.74954545 14.76037893]]


Index ile elemanlara erişmek

In [32]:
a=np.random.randint(10,size=10)
a[0]=12
print(a)
print(a[-1])
b=np.random.randint(13,size=(3,3))
print(b)
print(b[0,0])

[12  0  2  1  8  0  6  8  2  1]
1
[[12  7 11]
 [ 9  3 12]
 [ 8  5  9]]
12


Sciling ile elemanlara erişmek 

In [36]:
a=np.arange(20,30)
print(a[0:3])
print(a[:3])
print(a[3:])
print(a[: : 3])

[20 21 22]
[20 21 22]
[23 24 25 26 27 28 29]
[20 23 26 29]


In [41]:
b=np.random.randint(10,size=(5,5))
print(b)
print(b[ : ,0]) #her satırın sıfırıncı elemanını alır
print(b[1,:]) #her sütünun birinci elemanını aldı
print(b[ 0:2 ,0:3])

[[0 1 6 2 0]
 [4 5 6 4 4]
 [1 5 7 5 8]
 [2 6 7 0 2]
 [6 7 2 3 3]]
[0 4 1 2 6]
[4 5 6 4 4]
[[0 1 6]
 [4 5 6]]


Fancy Index 
bir liste içinden bu arrayden istediğmiz indisleri koyarak o indislerdeki verileri alabiliriz

In [43]:
yetgen=[1,3,5]
v=np.arange(0,30,3)
print(v)
print(v[yetgen])

[ 0  3  6  9 12 15 18 21 24 27]
[ 3  9 15]


Koşullu eleman işlemleri

In [53]:
n=np.array([1,2,3,4,5])
print(n>3)
print(n[n>3])
print(np.subtract(n,3))#her birinden üç çıkartır
print(np.add(n,2))#ekleme yapar
print(np.multiply(n,2))
print(np.divide(n,2))
print(np.power(n,2))
#diğer işlemler için ?np yaparsak gösteriri

[False False False  True  True]
[4 5]
[-2 -1  0  1  2]
[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]


İki bilinmeyenli denklem çözümü


In [57]:
a=np.array([[5,1],[1,3]])
b=np.array([12,10])
x=np.linalg.solve(a,b)
print(x)

[1.85714286 2.71428571]
