# Problem 1

In [6]:

import numpy as np
m=np.random.randint(10,size=5)
print(np.shape(m))
print(m.reshape(5))
print(m.ndim)
# 1 - numpy kütüphanesini import edin
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
# 3 - matris'in boyutunu öğrenin
# 4 - matris'i yeniden boyutlandırın
# 5 - matris'in boyut sayısını öğrenin


(5,)
[1 3 4 8 9]
1


# Problem 2

In [16]:
n=np.arange(1,10,2)
a,b,c=np.split(n,[1,3])
print(a , b , c )
print(np.concatenate([a,b,c]))
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
# 2 - Oluşturduğunuz matrisi parçalayı
# 3 - Parçalanmış matrisleri birleştirin


[1] [3 5] [7 9]
[1 3 5 7 9]


# Problem 3

In [46]:
a=np.random.choice(np.arange(1, 101, 2), size=10)
print(a)
print("Boyutu:",a.shape)
print("Boyut sayısı:",a.ndim)
print("Veri  tipi:",a.dtype)
print("Minumum:",np.min(a))
print("Maximum:",np.max(a))
print("Ortalama:",np.mean(a))
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
# 2 - matris'in özelliklerini inceleyin


[ 9 15 39 91 91 35 23 13 41  9]
Boyutu: (10,)
Boyut sayısı: 1
Veri  tipi: int64
Minumum: 9
Maximum: 91
Ortalama: 36.6
